### ISSUE TITLE
Indexing into a terminal is by column and row, not by row and column

### ISSUE THREAD

**Issue by jonastepe** [cpjreynolds/rustty#11]
From the documentation on the Terminal type I get that something like
```rust
term[(2, 3)]
```
returns the Cell at the third row and fourth column. However, it actually returns the Cell at the third column and fourth row. So it actually is
```rust
term[(x, y)]
```
rather than
```rust
term[(y, x)]
```
That is also reflected in the code. The docs are confusing here.

**Comment by cpjreynolds** [comment]
Sorry about this! Those docs are out of date at the moment, I'll get on that as soon as I can.

**Comment by cpjreynolds** [comment]
Closing this, fixed by 6451031.
