### ISSUE TITLE
multi-character grapheme support

### ISSUE THREAD

**Issue by orangea** [cpjreynolds/rustty#13]
This is an awesome library :) One thing that I want to ask though is, is there any plan to support putting multi-char graphemes inside of cells? For example the character `n̈` is encoded in unicode as the codepoint sequence `006E 0308`.

**Comment by cpjreynolds** [comment]
Thank you! I'm glad it can be of use.

I do plan on implementing more comprehensive unicode support in the near future, after the base functionality is worked out, additions like these will be much easier to add as the backend won't be as much of a moving target.

**Comment by cpjreynolds** [comment]
Closing now as #10 references the same issue.
