### ISSUE TITLE
How to build the examples?

### ISSUE THREAD

**Issue by matthiasbeyer** [cpjreynolds/rustty#28]

**Comment by Syntaf** [comment]
Do you have cargo installed? If you have cargo installed, run

`cargo run --example circle`

**Comment by matthiasbeyer** [comment]
Okay, worked for me.

Anyways,

- the `circle` example does not show a circle
- I don't know how to exit the textedit example

shall I submit issues for those?

**Comment by Syntaf** [comment]
Can you show me what the circle example looks like when you run it? Take a screenshot. 

To quit out of the text editor use the `\`` character

**Comment by matthiasbeyer** [comment]
![2016-01-05-210626_956x520_scrot](https://cloud.githubusercontent.com/assets/427866/12126229/36d00a5e-b3f0-11e5-9ee8-581eb47589d3.png)

> To quit out of the text editor use the ` character

Should be documented. At least the editor should print it before starting, so a user can read it while typing things, or something like that.

**Comment by Syntaf** [comment]
Interesting, that's definitely a bug. Go ahead and make an issue about it. Please include as much relevant information about it as you can about your environment.

**Comment by cpjreynolds** [comment]
Closing now as we can use issue #29 to track this bug.
