### ISSUE TITLE
How does it compare to rustbox(termbox)

### ISSUE THREAD

**Issue by mamciek** [cpjreynolds/rustty#31]
How does `rustty` compare to [rustbox](https://github.com/gchp/rustbox) or [termbox](https://github.com/nsf/termbox)? The concepts seems very similar: the cells end events. Can you describe what are the differences and similarities in concepts and internals?

**Comment by Syntaf** [comment]
Rustbox is a port of termbox with very minimal control over it's backend (minimal as in ... you have no access to the backend). You're only going to be able to do very trivial things with rustbox

Rustty is a ground up rust implementation of a terminal library, it's much more versatile and gives you a much wider range of possibilities. Take for example my [hacked up](https://github.com/Syntaf/ruik) clone of rustty which I use for widget based programming on projects likes [this](https://github.com/Syntaf/GameOfLife). 

I'd love to see widgets be implemented into rustty but the repo has gone cold for now, there's a barebones ui module but nothing really notable. 

I don't see any reason why rustbox should be used over rustty imo

**Comment by cpjreynolds** [comment]
@Syntaf puts it very well, and as a side note, the project is once again active :D closing this now.
