### ISSUE TITLE
Compilation with cargo build fails on Mac OS X, rustc 1.9: macro undefined: 'convert_ioctl_res!'

### ISSUE THREAD

**Issue by bomattin** [cpjreynolds/rustty#39]
Not sure why this is happening, since #[macro_use] is set up properly [here](https://github.com/cpjreynolds/rustty/blob/master/src/lib.rs#L18). Regardless, replicating this is as easy as git cloning this repo or creating an empty Cargo project with rustty as a dependency. Calling `cargo build` results in:

```
Compiling libc v0.2.12
   Compiling semver v0.1.20
   Compiling bitflags v0.4.0
   Compiling winapi v0.2.7
   Compiling winapi-build v0.1.1
   Compiling kernel32-sys v0.2.2
   Compiling term v0.4.4
   Compiling rustc_version v0.1.7
   Compiling rand v0.3.14
   Compiling nix v0.5.1
   Compiling tempfile v2.1.4
   Compiling gag v0.1.9
   Compiling rustty v0.1.11
/Users/bret.mattingly/.cargo/registry/src/github.com-88ac128001ac3a9a/rustty-0.1.11/src/core/termctl.rs:65:23: 65:40 error: macro undefined: 'convert_ioctl_res!'
/Users/bret.mattingly/.cargo/registry/src/github.com-88ac128001ac3a9a/rustty-0.1.11/src/core/termctl.rs:65         try!(unsafe { convert_ioctl_res!((ffi::ioctl(self.fd, ffi::TIOCGWINSZ, &mut ws))) });
                                                                                                                                 ^~~~~~~~~~~~~~~~~
error: aborting due to previous error
error: Could not compile `rustty`.
```

rustc version: 1.9.0 stable
Mac OSX version: 10.11.1 El Capitan

**Comment by cpjreynolds** [comment]
Thank you for reporting this! For some reason I thought I had merged my work on removing nix as a dependency, which fixes this, but now I see that was on a different project XD. I'll get on this right now, version 0.1.12 will have this fixed.

**Comment by cpjreynolds** [comment]
There we go, #40 should fix this issue. Closing it now but let me know if there are any other issues! Thank you.

**Comment by bomattin** [comment]
Flawless execution!
