### ISSUE TITLE
Arrow key support

### ISSUE THREAD

**Issue by stevebob** [cpjreynolds/rustty#43]
Currently pressing an arrow key is treated as 3 consecutive events. For example left arrow yields events `Ok(Some(Key('\u{1b}')))`, `Ok(Some(Key('[')))`, `Ok(Some(Key('D')))`. Is there a plan to add additional event types for non-char keys such as arrow keys?

**Comment by cpjreynolds** [comment]
Escape sequence processing is one of those things I've been putting off for far too long, I'm going to try and get on this today, it shouldn't be too difficult as all the information we need is held by the `Driver` struct.

At the moment most of my work is going into the `overhaul` branch, so I can merge all the big breaking changes at once in the near future; I'll be sure to keep this issue updated when I make some progress.

Thank you!

**Comment by stevebob** [comment]
https://github.com/cpjreynolds/rustty/pull/46

**Comment by cpjreynolds** [comment]
Closing this now, see #46
